export type Role = "guest" | "admin" | "secretary" | "associate_director";

const permissionMap: Record<Role, string[]> = {
  guest: ["entities:read", "deals:read", "purchases:read", "sales:read", "borrows:read", "vault:read"],
  admin: [
    "dashboard:read",
    "entities:read",
    "entities:create",
    "entities:update",
    "entities:delete",
    "deals:read",
    "deals:create",
    "deals:update",
    "deals:delete",
    "purchases:read",
    "purchases:create",
    "purchases:update",
    "purchases:delete",
    "sales:read",
    "sales:create",
    "sales:update",
    "sales:delete",
    "reports:read",
    "reminders:read",
    "borrows:read",
    "borrows:create",
    "borrows:update",
    "borrows:delete",
    "vault:read",
    "vault:deposit",
  ],
  secretary: [
    "dashboard:read",
    "entities:read",
    "entities:create",
    "entities:update",
    "deals:read",
    "deals:create",
    "purchases:read",
    "purchases:create",
    "purchases:update",
    "purchases:delete",
    "sales:read",
    "sales:create",
    "sales:update",
    "sales:delete",
    "reports:read",
    "reminders:read",
    "borrows:read",
    "borrows:create",
    "borrows:update",
    "borrows:delete",
    "vault:read",
    "vault:deposit",
  ],
  associate_director: [
    "dashboard:read",
    "entities:read",
    "deals:read",
    "deals:update",
    "purchases:read",
    "purchases:create",
    "sales:read",
    "sales:create",
    "reports:read",
    "reminders:read",
    "borrows:read",
    "borrows:create",
    "vault:read",
  ],
};

export function can(role: Role, permission: string): boolean {
  return permissionMap[role].includes(permission);
}

export const roleLabels: Record<Role, string> = {
  guest: "Guest",
  admin: "Admin",
  secretary: "Secretary",
  associate_director: "Associate Director",
};
